export type Pet = {
  id: string; 
  name: string; 
  breed: string;
  age: number; 
  amount: number; 
  location: string; 
  image: string;
  type: string; 
  gender?: string; 
  description?: string; 
  weight?: number; 
  vaccinated?: boolean; 
  userName?: string;
  userId:string;
  user?:string;
  adoptedBy?: string[]; 
  photoURL?:string;
  adoptionDate?: string; 
};
